### ISSUE TITLE
Not reviewed filter is not kept after rating the proposal

### ISSUE THREAD

**Issue by philippart-s** [conference-hall/conference-hall#286]
### What happened?

If I set the filter _Not reviewed_ and open the proposal for review if I set a note to a proposal the filter is reset to all proposals.

### Expected Behavior

For me the filter must be kept after setting the note to treat the next one.

### Your environment

Mac OSX and Firefox

**Comment by bpetetot** [comment]
Thanks for the feedback. It's fixed and will be released in the next production deployment.
