### ISSUE TITLE
JSON and Cards export are inverted

### ISSUE THREAD

**Issue by rverchere** [conference-hall/conference-hall#309]
### What happened?

On organizer proposal page, we can export talks to JSON or Cards format.
![image](https://github.com/user-attachments/assets/72f427ae-a8f8-4a55-b1ad-5816ee29a52b)

But the link are inverted : JSON produces Cards, and Cards produces JSON ;)

### Expected Behavior

JSON should produce JSON, Cards should produce Cards ;)

### Your environment

GNU/Linux with Chrome browser.

**Comment by rverchere** [comment]
Code confirms the issue:
https://github.com/conference-hall/conference-hall/blob/9fab405ac09dad7e1b1aec4f1a1c30dc7156d8eb/app/routes/team%2B/%24team.%24event%2B/reviews%2B/__components/proposals-list-page/actions/export-menu.tsx#L40

**Comment by bpetetot** [comment]
Hello, thanks for the feedback! It will be fixed quickly.

**Comment by bpetetot** [comment]
Fixed and deployed 😉 Thanks
