### ISSUE TITLE
Co-speaker disappears when session is updated

### ISSUE THREAD

**Issue by Zigotote** [conference-hall/conference-hall#363]
### What happened?

I submitted a session to a CFP with a co-speaker. 
A few days after I modified it's title and saved the change : it made my co-speaker disappear (his name no longer appears above the session's title). 
I had to invite him again with the "add speaker" link (which works great, by the way).

The same thing happens when I changed the talk's description. 

### Expected Behavior

The co-speaker should stay here

### Your environment

Chrome in MacOS Sequoia

**Comment by bpetetot** [comment]
Thanks for the report! We will investigate and check what happens.
